name: Building and Testing ðŸ

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # allow for workflow to be manually initiated from the Actions tab
  workflow_dispatch:

#build and test pySAR
jobs:
  build:

    name: Build and test pySAR
    runs-on: ubuntu-latest         # platform: [ubuntu-latest, macos-latest, windows-latest]
    strategy:
      matrix:
        python-version: [3.6,3.7, 3.8]   #testing on multiple python versions
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # install all required modules and dependancies using pip and setup.py installation
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install setuptools wheel twine
        pip install flake8 pytest
        pip3 install codecov
        pip3 install coverage
        pip3 install pytest
        pip3 install pytest-cov
        pip3 install bandit
        pip3 install safety
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python3 setup.py install

    #package vulnerability check
    - name: Package safety check
      run: |
       echo "Running package safety check"
       python3 -m safety check > package_safety_output.txt
       cat package_safety_output.txt
      continue-on-error: true

    #run Bandit security check for any known vulnerabilities in code
    - name: Bandit
      run: |
       echo "Running Bandit"
       python3 -m bandit -r . > bandit_output.txt
       cat bandit_output.txt
      continue-on-error: true

  # - pytest --cov-report term --cov=pySAR tests/
    - name: Lint with flake8
      run: |
        echo "Testing using flake8..."
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # unit tests using pytest, unittest, flake8 and bandit frameworks
    - name: Testing with unittest
      run: |
        echo "Testing using unittest..."
        python3 -m unittest discover

    - name: Test with pytest
      run: |
        echo "Testing using pytest..."
        python3 -m pytest tests/
        
    - name: Coverage Report
      run: |
        echo "Running coverage report..."
        pytest --cov-report term --cov=pySAR tests/
    # coveralls